apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - image: luxas/autoscale-demo:v0.1.2
        name: metrics-provider
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: sample-app
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: sample-app
spec:
  rules:
    - host: sample-app.plgrnd.be
      http:
        paths:
          - path: /
            backend:
              serviceName: sample-app
              servicePort: 80
---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  endpoints:
  - port: http