apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  # root password is required to be specified
  # lNohecTcJZJD9zN5WLHC8lJYjymtHBeMSQkUyMpn
  ROOT_PASSWORD: bE5vaGVjVGNKWkpEOXpONVdMSEM4bEpZanltdEhCZU1TUWtVeU1wbg==
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: db
  namespace: default
spec:
  replicas: 1
  secretName: mysql-secret
  mysqlVersion: "5.7"
  volumeSpec:
    emptyDir: {}
